/*
  Copyright (c) 2014-2015 Arduino LLC.  All right reserved.

  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.

  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  See the GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

#include "variant.h"
#include "sam.h"

/*
 * Pins descriptions
 */
const PinDescription g_APinDescription[]=
{
  // 0..1 
  // SERCOM/UART (Serial1)
  { PORTB, 21, PIO_SERCOM, PER_ATTR_SERCOM_STD, (PIN_ATTR_DIGITAL|PIN_ATTR_SERCOM), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_5, GCLK_CCL_NONE }, // RX0: SERCOM3/PAD[1]
  { PORTB, 20, PIO_SERCOM, PER_ATTR_SERCOM_STD, (PIN_ATTR_DIGITAL|PIN_ATTR_SERCOM), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_4, GCLK_CCL_NONE }, // TX0: SERCOM3/PAD[0]

  // 2..7
  // Digital Low
  { PORTA, 20, PIO_TIMER_PWM, PER_ATTR_TIMER_ALT, (PIN_ATTR_DIGITAL|PIN_ATTR_TIMER), TCC2_CH0, No_ADC_Channel, EXTERNAL_INT_4, GCLK_CCL_NONE }, // TCC2/WO[0]
  { PORTA, 21, PIO_TIMER_PWM, PER_ATTR_TIMER_ALT, (PIN_ATTR_DIGITAL|PIN_ATTR_TIMER), TCC2_CH1, No_ADC_Channel, EXTERNAL_INT_5, GCLK_CCL_NONE }, // TCC2/WO[1]
  { PORTA, 22, PIO_TIMER_PWM, PER_ATTR_TIMER_STD, (PIN_ATTR_DIGITAL|PIN_ATTR_TIMER|PIN_ATTR_COM), TC4_CH0, No_ADC_Channel, EXTERNAL_INT_6, GCLK_CCL_NONE },  // TC4/WO[0]
  { PORTA, 23, PIO_TIMER_PWM, PER_ATTR_TIMER_STD, (PIN_ATTR_DIGITAL|PIN_ATTR_TIMER|PIN_ATTR_COM), TC4_CH1, No_ADC_Channel, EXTERNAL_INT_7, GCLK_CCL_NONE }, // TC4/WO[1]
  { PORTA, 24, PIO_TIMER_PWM, PER_ATTR_TIMER_STD, (PIN_ATTR_DIGITAL|PIN_ATTR_TIMER|PIN_ATTR_COM), TC5_CH0, No_ADC_Channel, EXTERNAL_INT_12, GCLK_CCL_NONE }, // TC5/WO[0]
  { PORTA, 25, PIO_TIMER_PWM, PER_ATTR_TIMER_STD, (PIN_ATTR_DIGITAL|PIN_ATTR_TIMER|PIN_ATTR_COM), TC5_CH1, No_ADC_Channel, EXTERNAL_INT_13, GCLK_CCL_NONE }, // TC5/WO[1]

  // 8..12
  // Digital High
  { PORTB, 22, PIO_TIMER_PWM, PER_ATTR_TIMER_ALT, (PIN_ATTR_DIGITAL|PIN_ATTR_TIMER), TCC1_CH2, No_ADC_Channel, EXTERNAL_INT_6, GCLK_CCL_NONE }, // TCC1/WO[2]
  { PORTB, 23, PIO_TIMER_PWM, PER_ATTR_TIMER_ALT, (PIN_ATTR_DIGITAL|PIN_ATTR_TIMER), TCC1_CH3, No_ADC_Channel, EXTERNAL_INT_7, GCLK_CCL_NONE }, // TCC1/WO[3]
  { PORTA, 18, PIO_TIMER_PWM, PER_ATTR_TIMER_STD, (PIN_ATTR_DIGITAL|PIN_ATTR_TIMER), TC3_CH0, No_ADC_Channel, EXTERNAL_INT_2, GCLK_CCL_NONE }, // TC3/WO[0]
  { PORTA, 19, PIO_TIMER_PWM, PER_ATTR_TIMER_STD, (PIN_ATTR_DIGITAL|PIN_ATTR_TIMER), TC3_CH1, No_ADC_Channel, EXTERNAL_INT_3, GCLK_CCL_NONE }, // TC3/WO[1]
  { PORTB, 30, PIO_TIMER_PWM, PER_ATTR_TIMER_STD, (PIN_ATTR_DIGITAL|PIN_ATTR_TIMER), TC0_CH0, No_ADC_Channel, EXTERNAL_INT_14, GCLK_CCL_NONE }, // TC0/WO[0]

  // 13
  // LED
  { PORTB, 31, PIO_TIMER_PWM, PER_ATTR_TIMER_STD, (PIN_ATTR_DIGITAL|PIN_ATTR_TIMER), TC0_CH1, No_ADC_Channel, EXTERNAL_INT_15, GCLK_CCL_NONE }, // TC0/WO[1]

  // 14..21
  // Communication
  { PORTC, 24, PIO_SERCOM, PER_ATTR_SERCOM_STD, (PIN_ATTR_DIGITAL|PIN_ATTR_SERCOM), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_0, GCLK_CCL_NONE }, // TX3: SERCOM0/PAD[2]
  { PORTC, 25, PIO_SERCOM, PER_ATTR_SERCOM_STD, (PIN_ATTR_DIGITAL|PIN_ATTR_SERCOM), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_1, GCLK_CCL_NONE }, // RX3: SERCOM0/PAD[3]
  { PORTC, 27, PIO_SERCOM, PER_ATTR_SERCOM_ALT, (PIN_ATTR_DIGITAL|PIN_ATTR_SERCOM), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_3, GCLK_CCL_NONE }, // TX2: SERCOM1/PAD[0]
  { PORTC, 28, PIO_SERCOM, PER_ATTR_SERCOM_ALT, (PIN_ATTR_DIGITAL|PIN_ATTR_SERCOM), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_4, GCLK_CCL_NONE }, // RX2: SERCOM1/PAD[1]
  { PORTB, 18, PIO_SERCOM, PER_ATTR_SERCOM_ALT, (PIN_ATTR_DIGITAL|PIN_ATTR_SERCOM), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_2, GCLK_CCL_NONE }, // TX1: SERCOM3/PAD[2]
  { PORTB, 19, PIO_SERCOM, PER_ATTR_SERCOM_ALT, (PIN_ATTR_DIGITAL|PIN_ATTR_SERCOM), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_3, GCLK_CCL_NONE }, // RX1: SERCOM3/PAD[3]
  { PORTB, 16, PIO_SERCOM, PER_ATTR_SERCOM_STD, (PIN_ATTR_DIGITAL|PIN_ATTR_SERCOM), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_0, GCLK_CCL_NONE }, // SDA1: SERCOM5/PAD[0] 
  { PORTB, 17, PIO_SERCOM, PER_ATTR_SERCOM_STD, (PIN_ATTR_DIGITAL|PIN_ATTR_SERCOM), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_1, GCLK_CCL_NONE }, // SCL1: SERCOM5/PAD[1]

  // 22..53
  // Big header
  { PORTB,  3, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_3, GCLK_CCL_NONE },
  { PORTB,  2, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_2, GCLK_CCL_NONE },
  { PORTB,  1, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_1, GCLK_CCL_NONE },
  { PORTB,  0, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_0, GCLK_CCL_NONE },  // 25
  { PORTA, 28, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_8, GCLK_CCL_NONE },
  { PORTA, 27, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_15, GCLK_CCL_NONE },
  { PORTC, 26, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_2, GCLK_CCL_NONE },
  { PORTB, 25, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_9, GCLK_CCL_NONE },
  { PORTB, 24, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_8, GCLK_CCL_NONE },  // 30
  { PORTC, 21, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_13, GCLK_CCL_NONE },
  { PORTC, 20, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_12, GCLK_CCL_NONE },
  { PORTC, 19, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_11, GCLK_CCL_NONE },
  { PORTC, 18, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_12, GCLK_CCL_NONE },
  { PORTC, 17, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_9, GCLK_CCL_NONE },  // 35
  { PORTC, 16, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_8, GCLK_CCL_NONE },
  { PORTA, 17, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_1, GCLK_CCL_NONE },
  { PORTA, 16, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_0, GCLK_CCL_NONE },
  { PORTA, 15, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_15, GCLK_CCL_NONE },
  { PORTA, 14, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_14, GCLK_CCL_NONE },  // 40
  { PORTA, 13, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_13, GCLK_CCL_NONE },
  { PORTA, 12, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_12, GCLK_CCL_NONE },
  { PORTC, 15, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_7, GCLK_CCL_NONE },
  { PORTC, 14, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_6, GCLK_CCL_NONE },  
  { PORTC, 13, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_5, GCLK_CCL_NONE },  // 45
  { PORTC, 12, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_4, GCLK_CCL_NONE },
  { PORTB, 13, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL|PIN_ATTR_COM), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_13, GCLK_CCL_NONE },
  { PORTB, 11, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_11, GCLK_CCL_NONE },
  { PORTB, 10, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_10, GCLK_CCL_NONE },
  { PORTA, 11, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_11, GCLK_CCL_NONE },  // 50
  { PORTA, 10, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_10, GCLK_CCL_NONE },

  // 52..67 - 
  // Analog pins
  { PORTA,  2, PIO_ANALOG_ADC, PER_ATTR_ADC_STD, (PIN_ATTR_DIGITAL|PIN_ATTR_ANALOG), NOT_ON_TIMER, ADC_Channel0, EXTERNAL_INT_2, GCLK_CCL_NONE }, // A0
  { PORTC,  0, PIO_ANALOG_ADC, PER_ATTR_ADC_STD, (PIN_ATTR_DIGITAL|PIN_ATTR_ANALOG), NOT_ON_TIMER, ADC_Channel8, EXTERNAL_INT_8, GCLK_CCL_NONE }, // A1
  { PORTC,  1, PIO_ANALOG_ADC, PER_ATTR_ADC_STD, (PIN_ATTR_DIGITAL|PIN_ATTR_ANALOG), NOT_ON_TIMER, ADC_Channel9, EXTERNAL_INT_9, GCLK_CCL_NONE }, // A2
  { PORTC,  2, PIO_ANALOG_ADC, PER_ATTR_ADC_STD, (PIN_ATTR_DIGITAL|PIN_ATTR_ANALOG), NOT_ON_TIMER, ADC_Channel10, EXTERNAL_INT_10, GCLK_CCL_NONE }, // A3
  { PORTA,  8, PIO_ANALOG_ADC, PER_ATTR_ADC_ALT, (PIN_ATTR_DIGITAL|PIN_ATTR_ANALOG), NOT_ON_TIMER, ADC_Channel10, EXTERNAL_INT_NMI, GCLK_CCL_NONE }, // A4
  { PORTA,  9, PIO_ANALOG_ADC, PER_ATTR_ADC_ALT, (PIN_ATTR_DIGITAL|PIN_ATTR_ANALOG), NOT_ON_TIMER, ADC_Channel11, EXTERNAL_INT_9, GCLK_CCL_NONE }, // A5
  { PORTC,  3, PIO_ANALOG_ADC, PER_ATTR_ADC_STD, (PIN_ATTR_DIGITAL|PIN_ATTR_ANALOG), NOT_ON_TIMER, ADC_Channel11, EXTERNAL_INT_2, GCLK_CCL_NONE }, // A6
  { PORTB,  4, PIO_ANALOG_ADC, PER_ATTR_ADC_ALT, (PIN_ATTR_DIGITAL|PIN_ATTR_ANALOG), NOT_ON_TIMER, ADC_Channel6, EXTERNAL_INT_4, GCLK_CCL_NONE }, // A7
  { PORTB,  5, PIO_ANALOG_ADC, PER_ATTR_ADC_ALT, (PIN_ATTR_DIGITAL|PIN_ATTR_ANALOG), NOT_ON_TIMER, ADC_Channel7, EXTERNAL_INT_5, GCLK_CCL_NONE }, // A8
  { PORTB,  6, PIO_ANALOG_ADC, PER_ATTR_ADC_ALT, (PIN_ATTR_DIGITAL|PIN_ATTR_ANALOG), NOT_ON_TIMER, ADC_Channel8, EXTERNAL_INT_6, GCLK_CCL_NONE }, // A9
  { PORTB,  7, PIO_ANALOG_ADC, PER_ATTR_ADC_ALT, (PIN_ATTR_DIGITAL|PIN_ATTR_ANALOG), NOT_ON_TIMER, ADC_Channel9, EXTERNAL_INT_7, GCLK_CCL_NONE }, // A10
  { PORTB,  8, PIO_ANALOG_ADC, PER_ATTR_ADC_ALT, (PIN_ATTR_DIGITAL|PIN_ATTR_ANALOG), NOT_ON_TIMER, ADC_Channel4, EXTERNAL_INT_8, GCLK_CCL_NONE }, // A11
  { PORTB,  9, PIO_ANALOG_ADC, PER_ATTR_ADC_ALT, (PIN_ATTR_DIGITAL|PIN_ATTR_ANALOG), NOT_ON_TIMER, ADC_Channel5, EXTERNAL_INT_9, GCLK_CCL_NONE }, // A12
  { PORTA,  4, PIO_ANALOG_ADC, PER_ATTR_ADC_STD, (PIN_ATTR_DIGITAL|PIN_ATTR_ANALOG), NOT_ON_TIMER, ADC_Channel4, EXTERNAL_INT_4, GCLK_CCL_NONE }, // A13
  { PORTA,  5, PIO_ANALOG_ADC, PER_ATTR_ADC_STD, (PIN_ATTR_DIGITAL|PIN_ATTR_ANALOG), NOT_ON_TIMER, ADC_Channel5, EXTERNAL_INT_5, GCLK_CCL_NONE }, // A14
  { PORTA,  6, PIO_ANALOG_ADC, PER_ATTR_ADC_STD, (PIN_ATTR_DIGITAL|PIN_ATTR_ANALOG), NOT_ON_TIMER, ADC_Channel6, EXTERNAL_INT_6, GCLK_CCL_NONE }, // A15

  // 68..69 
  // I2C pins (SDA/SCL)
  { PORTC,  8, PIO_SERCOM, PER_ATTR_SERCOM_ALT, (PIN_ATTR_DIGITAL|PIN_ATTR_SERCOM), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_0, GCLK_CCL_NONE }, // SDA: SERCOM7/PAD[0]
  { PORTC,  9, PIO_SERCOM, PER_ATTR_SERCOM_ALT, (PIN_ATTR_DIGITAL|PIN_ATTR_SERCOM), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_1, GCLK_CCL_NONE }, // SCL: SERCOM7/PAD[1]

  // 70..72 - 
  // SPI pins (ICSP:MISO,SCK,MOSI)
  { PORTB, 12, PIO_SERCOM, PER_ATTR_SERCOM_ALT, (PIN_ATTR_DIGITAL|PIN_ATTR_SERCOM|PIN_ATTR_COM), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_12, GCLK_CCL_NONE }, // MISO: SERCOM4/PAD[0]
  { PORTB, 14, PIO_SERCOM, PER_ATTR_SERCOM_ALT, (PIN_ATTR_DIGITAL|PIN_ATTR_SERCOM|PIN_ATTR_COM), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_14, GCLK_CCL_NONE }, // MOSI: SERCOM4/PAD[2]
  { PORTB, 15, PIO_SERCOM, PER_ATTR_SERCOM_ALT, (PIN_ATTR_DIGITAL|PIN_ATTR_SERCOM|PIN_ATTR_COM), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_15, GCLK_CCL_NONE }, // SCK: SERCOM4/PAD[3]

  // 73..74
  // FTDI UART (USB)
  { PORTC,  6, PIO_SERCOM, PER_ATTR_SERCOM_STD, (PIN_ATTR_SERCOM), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_14, GCLK_CCL_NONE }, // TX: SERCOM6/PAD[0]
  { PORTC,  7, PIO_SERCOM, PER_ATTR_SERCOM_STD, (PIN_ATTR_SERCOM), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_15, GCLK_CCL_NONE }, // RX: SERCOM6/PAD[1]

  // 75
  // AREF
  { PORTA,  3, PIO_ANALOG_REF, PER_ATTR_ADC_STD, (PIN_ATTR_REF), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_3, GCLK_CCL_NONE }, // ADC-DAC/VREFA

  // 76
  // Alternate use of A0 (DAC output)
  { PORTA,  2, PIO_ANALOG_DAC, PER_ATTR_NONE, (PIN_ATTR_DAC), NOT_ON_TIMER, DAC_Channel0, EXTERNAL_INT_2, GCLK_CCL_NONE }, // DAC/VOUT
  
  // 77..78
  // Extra pins on internal header
  { PORTC, 10, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_2, GCLK_CCL_NONE },
  { PORTC, 11, PIO_MULTI, PER_ATTR_NONE, (PIN_ATTR_DIGITAL), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_3, GCLK_CCL_NONE },

  // 79..80
  // JTAG SWD 
  { PORTA, 30, PIO_COM, PER_ATTR_NONE, (PIN_ATTR_DIGITAL|PIN_ATTR_COM), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_10, GCLK_CCL_NONE }, // SWCLK
  { PORTA, 31, PIO_COM, PER_ATTR_NONE, (PIN_ATTR_DIGITAL|PIN_ATTR_COM), NOT_ON_TIMER, No_ADC_Channel, EXTERNAL_INT_11, GCLK_CCL_NONE }, // SWDIO
};

extern "C" {
    unsigned int PINCOUNT_fn() {
        return (sizeof(g_APinDescription) / sizeof(g_APinDescription[0]));
    }
}

const void* g_apTCInstances[TCC_INST_NUM+TC_INST_NUM]={ TCC0, TCC1, TCC2, TC0, TC1, TC2, TC3, TC4, TC5, TC6, TC7 } ;

SERCOM sercom0{ SERCOM0 } ;
SERCOM sercom1{ SERCOM1 } ;
SERCOM sercom2{ SERCOM2 } ;
SERCOM sercom3{ SERCOM3 } ;
SERCOM sercom4{ SERCOM4 } ;
SERCOM sercom5{ SERCOM5 } ;
SERCOM sercom6{ SERCOM6 } ;
SERCOM sercom7{ SERCOM7 } ;

Uart SerialUSB( &sercom6, PIN_SERIALUSB_RX, PIN_SERIALUSB_TX, PAD_SERIALUSB_RX, PAD_SERIALUSB_TX ) ;
Uart Serial( &sercom2, PIN_SERIAL_RX, PIN_SERIAL_TX, PAD_SERIAL_RX, PAD_SERIAL_TX ) ;
Uart Serial1( &sercom3, PIN_SERIAL1_RX, PIN_SERIAL1_TX, PAD_SERIAL1_RX, PAD_SERIAL1_TX ) ;
Uart Serial2( &sercom1, PIN_SERIAL2_RX, PIN_SERIAL2_TX, PAD_SERIAL2_RX, PAD_SERIAL2_TX ) ;
Uart Serial3( &sercom0, PIN_SERIAL3_RX, PIN_SERIAL3_TX, PAD_SERIAL3_RX, PAD_SERIAL3_TX ) ;

void SERCOM2_Handler()
{
  Serial.IrqHandler();
}

void SERCOM3_Handler()
{
  Serial1.IrqHandler();
}

void INT9_Handler()
{
  Serial3.IrqHandler();
  SerialUSB.IrqHandler();
}

void INT10_Handler()
{
  Serial2.IrqHandler();
}